// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnQYP4Cr1Jn4HeBoeSnesMZ_Eab0AfQzI',
    appId: '1:676626265004:web:8bbbcbc0829084e7bfc009',
    messagingSenderId: '676626265004',
    projectId: 'proj1-9bf49',
    authDomain: 'proj1-9bf49.firebaseapp.com',
    storageBucket: 'proj1-9bf49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyugeuaNQrz0c0pE8gQOwoRe5D4I83ngw',
    appId: '1:676626265004:android:c3dae2da55de22eebfc009',
    messagingSenderId: '676626265004',
    projectId: 'proj1-9bf49',
    storageBucket: 'proj1-9bf49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4shlW6ZJvh_Iy2VFxq2J2VYgW46ynA4E',
    appId: '1:676626265004:ios:2cdbc91c82422e92bfc009',
    messagingSenderId: '676626265004',
    projectId: 'proj1-9bf49',
    storageBucket: 'proj1-9bf49.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4shlW6ZJvh_Iy2VFxq2J2VYgW46ynA4E',
    appId: '1:676626265004:ios:2cdbc91c82422e92bfc009',
    messagingSenderId: '676626265004',
    projectId: 'proj1-9bf49',
    storageBucket: 'proj1-9bf49.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnQYP4Cr1Jn4HeBoeSnesMZ_Eab0AfQzI',
    appId: '1:676626265004:web:1a80c89471cb686bbfc009',
    messagingSenderId: '676626265004',
    projectId: 'proj1-9bf49',
    authDomain: 'proj1-9bf49.firebaseapp.com',
    storageBucket: 'proj1-9bf49.firebasestorage.app',
  );
}
